apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webserver
        image: mydockerrepo/image01:1.0 #kavyamsrini/my-app1:2.0.0
        ports:
        - containerPort: 8080
        
     
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: nodeport
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31111
